common: &common
  adapter: postgresql
  username: globabble
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: globabble_development

test:
  <<: *common
  database: globabble_test

production:
  <<: *common
  database: globabble_production
